**#This Code is Related to Upload code on s3 bucket via bitbucket pipeline**

**#Main Case - We have used Openid Connect to make communication beetween bitbucket and aws via role not credentials**

image: node:20

pipelines:
  branches:
    master:
          - step:
              name: Build and Test
              script:
                - npm install 
                - CI=false npm run build 
              artifacts:
                - build/**
          - step:
              name: Deploy to S3
              image: amazon/aws-cli
              oidc: true
              script:
                - export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token
                - echo $BITBUCKET_STEP_OIDC_TOKEN > $AWS_WEB_IDENTITY_TOKEN_FILE
                - export AWS_DEFAULT_REGION=us-east-1
                - export AWS_ROLE_ARN='arn:aws:iam::390403863665:role/Rlogical-Bitbucket-OID'
                - echo "Uploading artifacts to S3..."
                - aws s3 sync build/ s3://karan7990539526/
          - step:
              name: Invalidate CloudFront Cache
              oidc: true
              script:
                - pipe: atlassian/aws-cloudfront-invalidate:0.10.1
                  variables:
                    AWS_DEFAULT_REGION: 'us-east-1'
                    AWS_OIDC_ROLE_ARN: 'arn:aws:iam::390403863665:role/Rlogical-Bitbucket-OID'
                    DISTRIBUTION_ID: "E3PUA3PP19RJ6"
                    PATHS: '/*'  # Make sure the paths are passed as an array, even if it's just '/'
