**#This Code is Related to Upload code on s3 bucket via bitbucket pipeline**

**#Main Case - We have used Openid Connect to make communication beetween bitbucket and aws via role not credentials**

pipelines:
  branches:
    master:
          - step:
              name: Build and Test
              image: node:20
              script:
                - npm install 
                - CI=false npm run build 
              artifacts:
                - build/**
                
          - step:
              oidc: true
              script:
                - pipe: atlassian/aws-s3-deploy:1.6.1
                  variables:
                    AWS_DEFAULT_REGION: 'us-east-1'
                    AWS_OIDC_ROLE_ARN: 'arn:aws:iam::390403863665:role/Rlogical-Bitbucket-OID'
                    S3_BUCKET: 'karan7990539526'
                    LOCAL_PATH: 'build'

          - step:
              name: Invalidate CloudFront Cache
              oidc: true
              script:
                - pipe: atlassian/aws-cloudfront-invalidate:0.10.1
                  variables:
                    AWS_DEFAULT_REGION: 'us-east-1'
                    AWS_OIDC_ROLE_ARN: 'arn:aws:iam::390403863665:role/Rlogical-Bitbucket-OID'
                    DISTRIBUTION_ID: "E3PUA3PP19RJ6"
                    PATHS: '/*'  # Make sure the paths are passed as an array, even if it's just '/'
