name: CI/CD Pipeline for flowaud.io development

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest  # Adjust if needed for your environment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master  # Use the latest stable version
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          script: |
            cd /var/www/html/php_flowaudio
            git fetch --all
            git pull origin main
            git reset --hard origin/main

  Notification-task:
    runs-on: ubuntu-latest
    needs: Deploy  # Ensures this job runs after the Deploy job
    steps:
      - name: Notify Google Chat
        if: ${{ always() }}  # Ensures notification is sent regardless of success or failure
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}'
          jobStatus: '${{ job.status }}'
