name: CI/CD Pipeline for Frontend SAM1 Website

on:
  push:
    branches:
      - main

env:
  FRONTEND_DIR: /home/rlogical/test
  APP_NAME: sam1-frontend

jobs:
  Deploy:
    runs-on: ubuntu-latest  # Adjust if needed for your environment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USERNAME }}
          password: ${{ secrets.DEV_SERVER_PASSWORD }}

          script: |
            set -e
            echo "Navigating to frontend directory..."
            cd $FRONTEND_DIR
            ls -al
