name: CI/CD Pipeline for Frontend SAM1 Website

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest  # Adjust if needed for your environment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USERNAME }}
          password: ${{ secrets.DEV_SERVER_PASSWORD }}

          script: |
              cd /home/rlogical/test/
              git pull origin main
